### ISSUE TITLE
Add methods for proportions

### ISSUE THREAD

**Issue by chrismainey** [nhs-r-community/FunnelPlotR#10]
It is currently limited to standardised ratios, need to add the methods for proportions

**Comment by aghaynes** [comment]
Do you know how this goes? I'm having issues with rates vs population (due too narrow control limits as the poisson margins don't take dispersion into account appropriately...)

**Comment by chrismainey** [comment]
No progress on this I'm afraid. Too many other priorities at present.  I intend to look at it early next year. I was going to convert the binomial sections of Spieglehalter's papers, so the first stage was to generalise the functions to 'numerator' and 'denominator' etc. and so plot can be universal but data prep and limits different. I've done this part, but not written binomial methods yet.  Contributions welcome though.

**Comment by chrismainey** [comment]
Fixed by e7e34ecef08c2ac12d7a2eb5202fd90223b58d11. Proportion methods added to dev version.  Needs more testing though.
