### ISSUE TITLE
Vignette not working on github.io

### ISSUE THREAD

**Issue by simonthelwall** [nhs-r-community/FunnelPlotR#14]
The vignette does not work on [github.io](https://chrismainey.github.io/FunnelPlotR/index.html). I know I can find it on CRAN, but it would be kind of nice to access through the io pages too. 

https://chrismainey.github.io/FunnelPlotR/articles/funnel_plot.html

**Comment by chrismainey** [comment]
Hi, sorry for the late reply.  I thought I'be be notified of issues posted, but it mustn't be set up right.

That should be fixed now with commit: a1538c0c119b27fbc3362d41e24642da6b878622 .  It was just a missing s on a link name.
