### ISSUE TITLE
Add options to set colours of points. 

### ISSUE THREAD

**Issue by simonthelwall** [nhs-r-community/FunnelPlotR#43]
I think at the moment it is not possible to set the colours of the points. This would be a helpful addition

**Comment by chrismainey** [comment]
There is an option to do this in the development version on GitHub, but not CRAN I don't think.  I'm about to release an updated version to CRAN through.  the argument you need is `plot_cols = c(vector of colours)` . It's not a very elegant way to achieve it, but it works for now.
